# Generated by Django 3.2.16 on 2022-11-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnvbuildapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterbuild',
            name='build_gender',
        ),
        migrations.AddField(
            model_name='characterbuild',
            name='build_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
