# Generated by Django 3.2.16 on 2022-11-25 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnvbuildapp', '0003_auto_20221125_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterbuild',
            name='build_starting_skills',
        ),
        migrations.RemoveField(
            model_name='startingskills',
            name='barter',
        ),
        migrations.RemoveField(
            model_name='startingskills',
            name='energy_weapons',
        ),
        migrations.RemoveField(
            model_name='startingskills',
            name='explosives',
        ),
        migrations.RemoveField(
            model_name='startingskills',
            name='guns',
        ),
        migrations.RemoveField(
            model_name='startingskills',
            name='lockipick',
        ),
        migrations.RemoveField(
            model_name='startingskills',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='startingskills',
            name='melee_weapons',
        ),
        migrations.RemoveField(
            model_name='startingskills',
            name='repair',
        ),
        migrations.RemoveField(
            model_name='startingskills',
            name='science',
        ),
        migrations.RemoveField(
            model_name='startingskills',
            name='sneak',
        ),
        migrations.RemoveField(
            model_name='startingskills',
            name='speech',
        ),
        migrations.RemoveField(
            model_name='startingskills',
            name='survival',
        ),
        migrations.RemoveField(
            model_name='startingskills',
            name='unarmed',
        ),
        migrations.AddField(
            model_name='characterbuild',
            name='barter',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(52)]),
        ),
        migrations.AddField(
            model_name='characterbuild',
            name='energy_weapons',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(47)]),
        ),
        migrations.AddField(
            model_name='characterbuild',
            name='explosives',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(47)]),
        ),
        migrations.AddField(
            model_name='characterbuild',
            name='guns',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(47)]),
        ),
        migrations.AddField(
            model_name='characterbuild',
            name='lockipick',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(47)]),
        ),
        migrations.AddField(
            model_name='characterbuild',
            name='medicine',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(52)]),
        ),
        migrations.AddField(
            model_name='characterbuild',
            name='melee_weapons',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(47)]),
        ),
        migrations.AddField(
            model_name='characterbuild',
            name='repair',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(52)]),
        ),
        migrations.AddField(
            model_name='characterbuild',
            name='science',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(52)]),
        ),
        migrations.AddField(
            model_name='characterbuild',
            name='sneak',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(47)]),
        ),
        migrations.AddField(
            model_name='characterbuild',
            name='speech',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(52)]),
        ),
        migrations.AddField(
            model_name='characterbuild',
            name='survival',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(47)]),
        ),
        migrations.AddField(
            model_name='characterbuild',
            name='unarmed',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(47)]),
        ),
    ]
