# Generated by Django 3.2.16 on 2022-11-25 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnvbuildapp', '0004_auto_20221125_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterbuild',
            old_name='build_gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='characterbuild',
            old_name='build_perks',
            new_name='perks',
        ),
        migrations.RenameField(
            model_name='characterbuild',
            old_name='build_tag_skills',
            new_name='tag_skills',
        ),
        migrations.RenameField(
            model_name='characterbuild',
            old_name='build_traits',
            new_name='traits',
        ),
    ]
