# Generated by Django 3.2.16 on 2022-11-27 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnvbuildapp', '0005_auto_20221125_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterbuild',
            old_name='lockipick',
            new_name='lockpick',
        ),
    ]
