# Generated by Django 3.2.16 on 2022-11-27 18:44

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnvbuildapp', '0006_rename_lockipick_characterbuild_lockpick'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StartingSkills',
        ),
        migrations.AlterField(
            model_name='perks',
            name='perk_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='perks',
            name='perk_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Perk Image'),
        ),
        migrations.AlterField(
            model_name='tagskills',
            name='skill_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tagskills',
            name='skill_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Skill Image'),
        ),
    ]
