# Generated by Django 3.2.16 on 2022-11-27 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnvbuildapp', '0008_auto_20221127_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='charactercomment',
            new_name='character_build',
        ),
    ]
